#!/usr/bin/env bash
# kyzn/lib/report.sh — Before/after report + human changelog + PR creation

# ---------------------------------------------------------------------------
# Generate before/after report
# ---------------------------------------------------------------------------
generate_report() {
    local run_id="$1"
    local before_file="$2"
    local after_file="$3"
    local mode="$4"
    local focus="$5"

    ensure_kyzn_dirs

    local report_file="$KYZN_REPORTS_DIR/$run_id.md"
    # Compute before score fresh from before_file
    compute_health_score "$before_file"
    local before_score="${KYZN_HEALTH_SCORE:-0}"

    # Re-compute after score
    compute_health_score "$after_file"
    local after_score="${KYZN_HEALTH_SCORE:-0}"
    local delta=$(( after_score - before_score ))

    # Determine trend indicator
    local trend="→"
    if (( delta > 0 )); then trend="↑"; fi
    if (( delta < 0 )); then trend="↓"; fi

    # Generate diff summary (stage temporarily, excluding KyZN artifacts)
    local _add=0 _del=0 _bin=0
    count_diff_size _add _del _bin
    # Re-stage briefly to get --stat output
    stage_claude_changes
    local diff_stat
    diff_stat=$(git diff --cached --stat HEAD 2>/dev/null || echo "No changes")
    local files_changed
    files_changed=$(git diff --cached --name-only HEAD 2>/dev/null | wc -l)
    safe_git reset HEAD 2>/dev/null || true

    # Write report
    cat > "$report_file" <<EOF
# KyZN Improvement Report

**Run ID:** $run_id
**Date:** $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Mode:** $mode
**Focus:** $focus
**Cost:** \$${KYZN_CLAUDE_COST:-unknown}

## Health Score

| Before | After | Change |
|--------|-------|--------|
| $before_score | $after_score | $trend $delta |

## Changes Summary

Files changed: $files_changed

\`\`\`
$diff_stat
\`\`\`

## Category Scores

$(generate_category_comparison "$before_file" "$after_file")

---
*Generated by [KyZN](https://github.com/bokiko/KyZN) — autonomous code improvement*
EOF

    log_ok "Report saved to $report_file"

    # Create PR if trust mode allows (trust only from local.yaml, never committed config)
    local trust
    trust=$(local_config_get '.trust' 'guardian')

    # Stage Claude's changes only (excludes KyZN artifacts, secrets, CI files)
    stage_claude_changes
    safe_git commit -m "KyZN($mode): improve $focus [run:$run_id]

Health: $before_score → $after_score ($trend$delta)
Cost: \$${KYZN_CLAUDE_COST:-unknown}" 2>/dev/null || true

    # Push and create PR
    safe_git push -u origin HEAD 2>/dev/null || {
        log_warn "Could not push to remote. Create PR manually."
        return 1
    }

    local pr_body
    pr_body=$(generate_pr_body "$run_id" "$before_score" "$after_score" "$delta" "$mode" "$focus" "$diff_stat")

    local pr_url
    pr_url=$(gh pr create \
        --title "KyZN($mode): improve $focus — health $before_score → $after_score" \
        --body "$pr_body" \
        2>/dev/null) || {
        log_warn "Could not create PR. Create it manually."
        return 1
    }

    log_ok "PR created: $pr_url"

    # Auto-merge if autopilot mode
    if [[ "$trust" == "autopilot" ]]; then
        log_step "Autopilot mode: auto-merging..."
        gh pr merge --auto --squash "$pr_url" 2>/dev/null || {
            log_warn "Auto-merge failed. Merge manually."
        }
    fi
}

# ---------------------------------------------------------------------------
# Generate category comparison table
# ---------------------------------------------------------------------------
generate_category_comparison() {
    local before_file="$1"
    local after_file="$2"

    echo "| Category | Before | After | Change |"
    echo "|----------|--------|-------|--------|"

    # Pre-compute all 5 category scores per file in a single jq call each (10→2 jq spawns)
    local _jq_expr='. as $data |
        ["security","testing","performance","quality","documentation"] |
        map(. as $c |
            [$data[] | select(.category == $c)] |
            if length > 0 then
                (([.[].score] | add) * 100 / ([.[].max_score] | add) | tostring)
            else "-" end
        ) | @tsv'
    local before_tsv after_tsv
    before_tsv=$(jq -r "$_jq_expr" "$before_file" 2>/dev/null) || before_tsv="-	-	-	-	-"
    after_tsv=$(jq -r "$_jq_expr" "$after_file" 2>/dev/null) || after_tsv="-	-	-	-	-"

    local bsec btest bperf bqual bdoc asec atest aperf aqual adoc
    IFS=$'\t' read -r bsec btest bperf bqual bdoc <<< "$before_tsv"
    IFS=$'\t' read -r asec atest aperf aqual adoc <<< "$after_tsv"

    local _cats=(security testing performance quality documentation)
    local _bvals=("$bsec" "$btest" "$bperf" "$bqual" "$bdoc")
    local _avals=("$asec" "$atest" "$aperf" "$aqual" "$adoc")

    local idx=0
    for cat in "${_cats[@]}"; do
        local before_val="${_bvals[$idx]}"
        local after_val="${_avals[$idx]}"
        ((idx++)) || true

        if [[ "$before_val" != "-" && "$after_val" != "-" && -n "$before_val" && -n "$after_val" ]]; then
            local bv="${before_val%.*}"; bv="${bv:-0}"
            local av="${after_val%.*}"; av="${av:-0}"
            local d=$(( av - bv ))
            local t="→"
            if (( d > 0 )); then t="↑ +$d"
            elif (( d < 0 )); then t="↓ $d"
            fi
            echo "| $cat | $before_val | $after_val | $t |"
        elif [[ "$before_val" != "-" ]]; then
            echo "| $cat | $before_val | - | - |"
        fi
    done
}

# ---------------------------------------------------------------------------
# Generate PR body
# ---------------------------------------------------------------------------
generate_pr_body() {
    local run_id="$1"
    local before="$2"
    local after="$3"
    local delta="$4"
    local mode="$5"
    local focus="$6"
    local diff_stat="$7"

    local trend="→"
    if (( delta > 0 )); then trend="↑"
    elif (( delta < 0 )); then trend="↓"
    fi

    cat <<EOF
## KyZN Improvement Report

**Health Score:** $before → $after ($trend $delta)
**Mode:** $mode | **Focus:** $focus
**Cost:** \$${KYZN_CLAUDE_COST:-unknown}
**Run ID:** \`$run_id\`

### Changes
\`\`\`
$diff_stat
\`\`\`

### Verification
- Build: ✅ Passed
- Tests: ✅ Passed

---

To approve: \`kyzn approve $run_id\`
To reject: \`kyzn reject $run_id --reason "..."\`

*Generated by [KyZN](https://github.com/bokiko/KyZN) — autonomous code improvement*
EOF
}
