#!/usr/bin/env bash
# kyzn/lib/report.sh — Before/after report + human changelog + PR creation

# ---------------------------------------------------------------------------
# Generate before/after report
# ---------------------------------------------------------------------------
generate_report() {
    local run_id="$1"
    local before_file="$2"
    local after_file="$3"
    local mode="$4"
    local focus="$5"

    ensure_kyzn_dirs

    local report_file="$KYZN_REPORTS_DIR/$run_id.md"
    # Compute before score fresh from before_file
    compute_health_score "$before_file"
    local before_score="${KYZN_HEALTH_SCORE:-0}"

    # Re-compute after score
    compute_health_score "$after_file"
    local after_score="${KYZN_HEALTH_SCORE:-0}"
    local delta=$(( after_score - before_score ))

    # Determine trend indicator
    local trend="→"
    if (( delta > 0 )); then trend="↑"; fi
    if (( delta < 0 )); then trend="↓"; fi

    # Generate diff summary
    local diff_stat
    diff_stat=$(git diff --stat HEAD 2>/dev/null || echo "No changes")
    local files_changed
    files_changed=$(git diff --name-only HEAD 2>/dev/null | wc -l)

    # Write report
    cat > "$report_file" <<EOF
# kyzn Improvement Report

**Run ID:** $run_id
**Date:** $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Mode:** $mode
**Focus:** $focus
**Cost:** \$${KYZN_CLAUDE_COST:-unknown}

## Health Score

| Before | After | Change |
|--------|-------|--------|
| $before_score | $after_score | $trend $delta |

## Changes Summary

Files changed: $files_changed

\`\`\`
$diff_stat
\`\`\`

## Category Scores

$(generate_category_comparison "$before_file" "$after_file")

---
*Generated by [kyzn](https://github.com/bokiko/kyzn) — autonomous code improvement*
EOF

    log_ok "Report saved to $report_file"

    # Create PR if trust mode allows
    local trust
    trust=$(config_get '.preferences.trust' 'guardian')

    # Commit changes (only tracked files, not untracked)
    git add -u 2>/dev/null
    git commit -m "kyzn($mode): improve $focus [run:$run_id]

Health: $before_score → $after_score ($trend$delta)
Cost: \$${KYZN_CLAUDE_COST:-unknown}" 2>/dev/null || true

    # Push and create PR
    git push -u origin HEAD 2>/dev/null || {
        log_warn "Could not push to remote. Create PR manually."
        return 1
    }

    local pr_body
    pr_body=$(generate_pr_body "$run_id" "$before_score" "$after_score" "$delta" "$mode" "$focus" "$diff_stat")

    local pr_url
    pr_url=$(gh pr create \
        --title "kyzn($mode): improve $focus — health $before_score → $after_score" \
        --body "$pr_body" \
        2>/dev/null) || {
        log_warn "Could not create PR. Create it manually."
        return 1
    }

    log_ok "PR created: $pr_url"

    # Auto-merge if autopilot mode
    if [[ "$trust" == "autopilot" ]]; then
        log_step "Autopilot mode: auto-merging..."
        gh pr merge --auto --squash "$pr_url" 2>/dev/null || {
            log_warn "Auto-merge failed. Merge manually."
        }
    fi
}

# ---------------------------------------------------------------------------
# Generate category comparison table
# ---------------------------------------------------------------------------
generate_category_comparison() {
    local before_file="$1"
    local after_file="$2"

    echo "| Category | Before | After | Change |"
    echo "|----------|--------|-------|--------|"

    for cat in security testing performance quality documentation; do
        local before_val after_val
        before_val=$(jq -r --arg c "$cat" '[.[] | select(.category == $c) | .score] | (add / length) // "-"' "$before_file" 2>/dev/null)
        after_val=$(jq -r --arg c "$cat" '[.[] | select(.category == $c) | .score] | (add / length) // "-"' "$after_file" 2>/dev/null)

        if [[ "$before_val" != "-" && "$after_val" != "-" && -n "$before_val" && -n "$after_val" ]]; then
            local bv="${before_val%.*}"; bv="${bv:-0}"
            local av="${after_val%.*}"; av="${av:-0}"
            local d=$(( av - bv ))
            local t="→"
            (( d > 0 )) && t="↑ +$d"
            (( d < 0 )) && t="↓ $d"
            echo "| $cat | $before_val | $after_val | $t |"
        elif [[ "$before_val" != "-" ]]; then
            echo "| $cat | $before_val | - | - |"
        fi
    done
}

# ---------------------------------------------------------------------------
# Generate PR body
# ---------------------------------------------------------------------------
generate_pr_body() {
    local run_id="$1"
    local before="$2"
    local after="$3"
    local delta="$4"
    local mode="$5"
    local focus="$6"
    local diff_stat="$7"

    local trend="→"
    (( delta > 0 )) && trend="↑"
    (( delta < 0 )) && trend="↓"

    cat <<EOF
## kyzn Improvement Report

**Health Score:** $before → $after ($trend $delta)
**Mode:** $mode | **Focus:** $focus
**Cost:** \$${KYZN_CLAUDE_COST:-unknown}
**Run ID:** \`$run_id\`

### Changes
\`\`\`
$diff_stat
\`\`\`

### Verification
- Build: ✅ Passed
- Tests: ✅ Passed

---

To approve: \`kyzn approve $run_id\`
To reject: \`kyzn reject $run_id --reason "..."\`

*Generated by [kyzn](https://github.com/bokiko/kyzn) — autonomous code improvement*
EOF
}
